### ISSUE TITLE
GitHub-Pages not activated

### ISSUE THREAD

**Issue by t-huyeng** [bundesAPI/pflanzenschutzmittelzulassung-api#2]
For this repo GitHub-Pages is not activated.

**Comment by wirthual** [comment]
I see. I activated it for the main branch, it tells me now it does an DNS check.

Are there additional steps required?

**Comment by t-huyeng** [comment]
Can you try to activate this (if not activate):
![image](https://user-images.githubusercontent.com/39559223/224353156-58266e6d-302e-4146-8c53-82370369d658.png)
I have seen the same error on the Regionalatlas repo. 

The action is deploying the page to `http`
![image](https://user-images.githubusercontent.com/39559223/224353575-263092c9-8799-4b63-9fbb-a075738fa2b4.png)

This may cause the error.

@wirthual did you change this setting? If yes this might helps fixing the error at Regionalatlas as well.

**Comment by t-huyeng** [comment]
It works now!🚀 
https://pflanzenschutzmittelzulassung.api.bund.dev/

**Comment by t-huyeng** [comment]
But it looks like we have a lot of encoding errors regarding umlauts in the current version.

**Comment by wirthual** [comment]
Good catch. Lets track it in  #3
